// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetSettings():Promise<main.Config>;

export function Greet(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.Config):Promise<void>;

export function TestProxyConnection(arg1:string):Promise<string>;

export function TranscribeAudio(arg1:string,arg2:string):Promise<string>;
