// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ResetStatistics() {
  return window['go']['main']['App']['ResetStatistics']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function TestProxyConnection(arg1) {
  return window['go']['main']['App']['TestProxyConnection'](arg1);
}

export function TranscribeAudio(arg1, arg2) {
  return window['go']['main']['App']['TranscribeAudio'](arg1, arg2);
}
